/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/auth/signup/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          content: {
            "application/json": {
              firstName: string;
              lastName: string;
              /** Format: email */
              email: string;
              sub: string;
            };
          };
        };
      };
    };
  };
  "/api/comments/{commentId}/": {
    delete: {
      parameters: {
        path: {
          commentId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    patch: {
      parameters: {
        path: {
          commentId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              text: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: uuid */
              authorId: string | null;
            };
          };
        };
      };
    };
  };
  "/api/posts/": {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          cursorCreatedAt?: string;
          cursorId?: string;
          search?: string;
          sortBy?: "title" | "createdAt" | "commentsCount";
          sortOrder?: "asc" | "desc";
          minCommentsCount?: number;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: ({
                  /** Format: uuid */
                  id: string;
                  title: string;
                  description: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: uuid */
                  authorId: string | null;
                  commentsCount: number;
                })[];
              meta: {
                totalCount: number;
                totalPages: number;
                page: number;
                pageSize: number;
              };
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: uuid */
              authorId: string | null;
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: uuid */
              authorId: string | null;
              comments: ({
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: uuid */
                  authorId: string | null;
                })[];
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    patch: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: uuid */
              authorId: string | null;
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                /** Format: uuid */
                id: string;
                text: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: uuid */
                authorId: string | null;
              })[];
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              text: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: uuid */
              authorId: string | null;
            };
          };
        };
      };
    };
  };
  "/api/user/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              sub: string;
              firstName: string;
              lastName: string;
              /** Format: email */
              email: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description - GENERAL_ERROR -> 1000
     * @enum {integer}
     */
    ErrorCodes: 1000;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
